### ISSUE TITLE
openunison to keycloak redirect failing  

### ISSUE THREAD

**Issue by SinghDivneet** [OpenUnison/openunison-k8s#15]
Keep getting the following error.

`  Invalid parameter: redirect_uri` 

<img width="761" alt="Screenshot 2022-01-26 at 1 33 29 AM" src="https://user-images.githubusercontent.com/40354269/151052019-dd24222c-340b-408d-8719-8ccda8af91a2.png">

**This is what the current redirect value looks like.** 
 
<img width="1092" alt="Screenshot 2022-01-26 at 1 40 10 AM" src="https://user-images.githubusercontent.com/40354269/151052007-761cacd4-5f63-47da-ba27-de6f64f69726.png">

**Comment by mlbiam** [comment]
The `Valid Redirect URLs` configuration should be `https://openunisonhost/auth/oidc`

**Comment by SinghDivneet** [comment]
Fixed that getting, thank you for handholding here.

<img width="1092" alt="Screenshot 2022-01-26 at 1 48 48 AM" src="https://user-images.githubusercontent.com/40354269/151053035-f6838e5a-65d4-45a0-b5b6-c39f43656459.png">

**Comment by SinghDivneet** [comment]
This is the error message in the logs 

```[2022-01-25 20:20:18,901][XNIO-1 task-7] ERROR OpenIDConnectAuthMech - Could not retrieve token : 400 / Bad Request
[2022-01-25 20:20:18,901][XNIO-1 task-7] INFO  AccessLog - [AuFail] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - cn=none - enterprise-idp [10.1.2.202] - [feccbc45e9d60f018f9f9be308e36551193704f77]
[2022-01-25 20:20:19,163][XNIO-1 task-7] INFO  AccessLog - [Error] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - uid=Anonymous,o=Tremolo - NONE [10.1.2.202] - [feccbc45e9d60f018f9f9be308e36551193704f77]
[2022-01-25 20:20:19,164][XNIO-1 task-7] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Could not load user data
	at com.tremolosecurity.unison.proxy.auth.openidconnect.OpenIDConnectAuthMech.doGet(OpenIDConnectAuthMech.java:334) ~[unison-auth-openidconnect-1.0.24.jar:?]
	at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:191) ~[unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) ~[unison-sdk-1.0.24.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:88) ~[unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:296) [unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.24.jar:?]
	at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) [unison-server-core-1.0.24.jar:?]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) [xnio-api-3.8.4.Final.jar:3.8.4.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.Exception: Could not retrieve token : 401 / Unauthorized
	at com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadAttributesFromWS.loadUserAttributesFromIdP(LoadAttributesFromWS.java:66) ~[unison-auth-openidconnect-1.0.24.jar:?]
	at com.tremolosecurity.unison.proxy.auth.openidconnect.OpenIDConnectAuthMech.doGet(OpenIDConnectAuthMech.java:332) ~[unison-auth-openidconnect-1.0.24.jar:?]```

**Comment by mlbiam** [comment]
Take a look at the keycloak logs.  My guess is your client secret is wrong or your client id (or both)

**Comment by SinghDivneet** [comment]
Turns out I didn't add the `client secret` after doing that & setting `enable_impersonation` to `true` 

Still getting a similar error. 

```	... 44 more
[2022-01-25 21:12:35,621][XNIO-1 task-14] ERROR OpenIDConnectAuthMech - Could not retrieve token : 401 / Unauthorized
[2022-01-25 21:12:35,622][XNIO-1 task-14] INFO  AccessLog - [AuFail] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - cn=none - enterprise-idp [10.1.2.202] - [fa3ad5d5c33472c402fa59c4870c6f660611d2ae9]
[2022-01-25 21:12:35,881][XNIO-1 task-14] INFO  AccessLog - [Error] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - uid=Anonymous,o=Tremolo - NONE [10.1.2.202] - [fa3ad5d5c33472c402fa59c4870c6f660611d2ae9]
[2022-01-25 21:12:35,881][XNIO-1 task-14] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Could not load user data```

**Comment by SinghDivneet** [comment]
Updated log line 

`[2022-01-25 21:30:05,829][XNIO-1 task-2] INFO  AccessLog - [AzSuccess] - root-redirect - https://openunison.testauth.enthires.com/ - uid=Anonymous,o=Tremolo - scale-redirect [10.1.2.202] - [ffc9f7c347cd427358db39cb847af3f489def8598]
[2022-01-25 21:30:08,119][XNIO-1 task-2] ERROR OpenIDConnectAuthMech - Could not retrieve token : 401 / Unauthorized
[2022-01-25 21:30:08,119][XNIO-1 task-2] INFO  AccessLog - [AuFail] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - cn=none - enterprise-idp [10.1.2.202] - [faaacbb1d42e6b9c9be8cad7dd3fa4ddcbfd9b868]
[2022-01-25 21:30:08,410][XNIO-1 task-2] INFO  AccessLog - [Error] - completelogin - https://openunison.testauth.enthires.com/auth/oidc - uid=Anonymous,o=Tremolo - NONE [10.1.2.202] - [faaacbb1d42e6b9c9be8cad7dd3fa4ddcbfd9b868]
[2022-01-25 21:30:08,411][XNIO-1 task-2] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Could not load user data`

**Comment by mlbiam** [comment]
did you setup keycloak for groups? (https://openunison.github.io/identity%20providers/keycloak/)

**Comment by SinghDivneet** [comment]
Yes i did

**Comment by SinghDivneet** [comment]
Also if you can correct the group name according to this `Out of the box, keycloak assigns group names as the name of the group after a "/". So in your RBAC bindings you'll use that instead of just the name of the group` 


Here 

```kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: activedirectory-cluster-admins
subjects:
- kind: Group
  name: k8s-admins
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io```

**Comment by SinghDivneet** [comment]
nevermind it worked
