### ISSUE TITLE
Webhook error when deploying on bare metal k8s cluster

### ISSUE THREAD

**Issue by BrentRose** [OpenUnison/openunison-k8s#49]
I've been able to deploy OU on a local minikube cluster fine.  In this local test I'm using a self signed CA with a cert/key I've generated from it.  When I try to deploy to a bare metal cluster I'm getting the following error.

2022/07/08 20:26:18 warning: Upgrade "orchestra-login-portal" failed: failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s": x509: certificate signed by unknown authority
panic: failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s": x509: certificate signed by unknown authority

I've created the ou-tls-certificate secret with the full chain (root/intermediate/issuing/cert) and the key.  This is different from my minikube test where I only had a root (no intermediate or issuing).

In my values.yaml file I added the unison-ca in the trusted_certs section.  I've tried to use the root as well as issuing cert here but both had the same result.

My cert includes SANs for my k8sou and k8sdb sites.

My ingress seems to work prior to installing ou.

I'm probably missing something silly but I haven't been able to figure it out.

**Comment by mlbiam** [comment]
> 2022/07/08 20:26:18 warning: Upgrade "orchestra-login-portal" failed: failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "[https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s](https://openunison-orchestra.openunison.svc/k8s/webhooks/v1/applications?timeout=5s)": x509: certificate signed by unknown authority
panic: failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "[https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s](https://openunison-orchestra.openunison.svc/k8s/webhooks/v1/applications?timeout=5s)": x509: certificate signed by unknown authority

This happens when the `orchestra-login-portal` chart is deployed before the new `openunison-orchestra` `Pod` is in a ***Ready*** state.  

Kubernetes requires you to have a certificate for admission controller configuration, but it's bad form to embed a certificate in your helm charts, so to configure the admission controller that validates OpenUnison's configuration objects the helm chart templet embeds a dummy cert in the `ValidatingWebhookConfiguration` configuration's `caBundle` attribute for each webhook, then the operator updates the `ValidatingWebhookConfiguration` with the certificate from the `unison-tls` `Secret` (not `ou-tls-certificate`).  The `unison-tls` certificate is used by the OpenUnison `Pod`, but doesn't get included in `Ingress`.  Since the API server needs to explicitly trust the admission controller's cert, `unison-tls` needs to be used for each deployment.

Are you deploying the charts manually or using the `ouctl` tool?

**Comment by BrentRose** [comment]
@mlbiam I'm using ouctl

**Comment by BrentRose** [comment]
Does this mean I should deploy without ou-tls-cetificate an then follow the process to update it via https://openunison.github.io/knowledgebase/certificates/ ?

**Comment by mlbiam** [comment]
> At this point I'd expect the portal to be up but nginx is still using default cert and says k8sou-vmt.qa.local isn't found.

Can you post your values.yaml?

> Note: I do NOT set the api_server_host. I didn't use this in my local testing so I don't think it's necessary. Correct me if I'm wrong.

You need this setting if you want your API server to integrate with OpenUnison via OIDC.  If you set `enable_impersonation` to `true` this value gets ignored.

> If I look at the openunison-operator logs I see the following repeated:
```
[2022-07-11 14:52:41,125][XNIO-1 task-6] INFO AccessLog - [Error] - UNKNOWN - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - cn=none - NONE [127.0.0.1] - [f105ab0a8b812f65cbb5e242f35c7314fa3683878] [2022-07-11 14:52:41,125][XNIO-1 task-6] ERROR ConfigSys - Could not process request javax.servlet.ServletException: Unknown URI : /auth/idp/k8sIdp/.well-known/openid-configuration
```

Even after updating the `orchestra-login-portal` helm chart?

**Comment by BrentRose** [comment]
`network:
  openunison_host: "k8sou-vmt.qa.local"
  dashboard_host: "k8sdb-vmt.qa.local"
  api_server_host: "k8sapi.apps.ou.tremolo.dev"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://atl1vmtk8s.qa.local:6443
  force_redirect_to_tls: false
  createIngressCertificate: false
  ingress_type: nginx
  ingress_annotations: {}

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"


image: docker.io/tremolosecurity/openunison-k8s
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: false

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  require_session: true

certs:
  use_k8s_cm: false

trusted_certs:
  - name: unison-ca
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZOVENDQkIyZ0F3SUJBZ0lUWkFBQXpET0tjWVVuN2RXa05BQUNBQURNTXpBTkJna3Foa2lHOXcwQkFRc0YKQURCZU1Rc3dDUVlEVlFRR0V3SlZVekVkTUJzR0ExVUVDaE1VYzJGc1pYTm1iM0pqWlM1amIyMHNJR2x1WXk0eApHREFXQmdOVkJBc1REMDFoY210bGRHbHVaeUJEYkc5MVpERVdNQlFHQTFVRUF4TU5VMFpOUXlCUlFTQlVURk13Ck1UQWVGdzB5TWpBek16RXdORE0wTVRoYUZ3MHlNekF4TWpjeE9EUTROVFphTUlHRE1Rc3dDUVlEVlFRR0V3SlYKVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeVlXNWphWE5qYnpFZApNQnNHQTFVRUNoTVVjMkZzWlhObWIzSmpaUzVqYjIwc0lHbHVZeTR4RFRBTEJnTlZCQXNUQkZaSlVGTXhHVEFYCkJnTlZCQU1URUhadGRDMXdiMk11Y1dFdWJHOWpZV3d3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUM2cVowTFpvbmJoOElKNUV3ZWdkVXRjWVkxM3JKblhac0ZhM3dGaHBONE9VdXg4VHJpdzc3WQo1V3ZzRTREdk5BakM2a2M4aU1pMzJVb3IzbkJ5M1N6RFBBRzRxcmw1K1JQbXQxbzZvSm0wdFpoalA5dlZuZitFCnBmUEh6b1paejE2aXBoTUl0YU5iL3Y4QS8zVUZ1MmdVQ0lqTWZMY0dxVHN0T1MwaTBpbEFTL2h2NGU4VnNTdXUKUDc4Z1paa3JCTWM2U3FJak95T2gwTERIS25RYjNhbnlWRzUrcUVJOXhRZjVOSm85bkMwZGEzc2JtSGZYM0tvagpoVisxVlpvK3E4UFAxVWUvTzZXaUN4eFF6NUtMb1ZpbHFWQU5zbG1CckdWa25iTkNZa2N4SnM3RVg1ZFlEVjNhCmlCRGtyN0hvb3ZYRW9wRTRLcnJrQzhXZXBKTGNoVFVmQWdNQkFBR2pnZ0hFTUlJQndEQldCZ05WSFJFRVR6Qk4KZ2hGbmJIVjFMWFp0ZEM1eFlTNXNiMk5oYklJU2F6aHpiM1V0ZG0xMExuRmhMbXh2WTJGc2doSnJPSE5rWWkxMgpiWFF1Y1dFdWJHOWpZV3lDRUhadGRDMXdiMk11Y1dFdWJHOWpZV3d3SFFZRFZSME9CQllFRkFYK1J2alVOLyt2CjhvN3kxWE5UTkU5VTBTQjZNQjhHQTFVZEl3UVlNQmFBRk9MRnlxTllsdzhyb1llRENZcG5zS1FJeEI3MU1Ea0cKQTFVZEh3UXlNREF3THFBc29DcUdLR2gwZEhBNkx5OXdhMmt1Y1dFdWJHOWpZV3d2VTBaTlF5MVJRUzFVVEZNdwpNU2d5S1M1amNtd3dhZ1lJS3dZQkJRVUhBUUVFWGpCY01EUUdDQ3NHQVFVRkJ6QUNoaWhvZEhSd09pOHZjR3RwCkxuRmhMbXh2WTJGc0wxTkdUVU10VVVFdFZFeFRNREVvTWlrdVkzSjBNQ1FHQ0NzR0FRVUZCekFCaGhob2RIUncKT2k4dmNHdHBMbkZoTG14dlkyRnNMMjlqYzNBd0RnWURWUjBQQVFIL0JBUURBZ1dnTUQwR0NTc0dBUVFCZ2pjVgpCd1F3TUM0R0ppc0dBUVFCZ2pjVkNJTEU1a3lFdE9KOWc3MmRHb2VmdDF5Q3haaEJMWUtFaEJTQjRxUTBBZ0ZrCkFnRUxNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUJzR0NTc0dBUVFCZ2pjVkNnUU9NQXd3Q2dZSUt3WUIKQlFVSEF3RXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTEpHYjdRdFNwSDllRGxRT2xPaExMcTRhUGJOUDdwRQo4V3YwelA1ek8xQ2N4RkdSbXQ1d2l4YTAvbGJ5Q0xzUi84T3FEeU5BZzhtNkY1MXo5WkM0NlM3QjlrSlZHcDBGCmo1ajBTRnRwb3NCL3Q0MVJpUzRCU2NRc25oSjRtc2ZycUFKaE5FWS84VTlkL2hLU25iZThaMlUrbGZwd202T0UKWVRBY01qdjgvLzl5TDQ0VUNSZTR0akQzMjhjd2xTcDkvck5ZRFo2ME9EZU90TzBVWVhCOGhPSEM4MFl0NGNiYwppOTVjUTY2NlNRU21qNWRsL1BpS2pKUzJYbWtUclE0NDRuOFVQbmpPaExOajlla0NackFEcTJFMTRFN1B4ZzNBCk1MSzEweUtnTEpWSzlRdGVoS1VxckEvL3V5QVhwdEErVWczT05BNEJ0TjJOMlRzdEN4c1NXMkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

  - name: ldaps
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lRYlJOajZSS3F0cVZQdlc2NXFaeFhYakFOQmdrcWhraUc5dzBCQVFVRkFEQWkKTVNBd0hnWURWUVFEREJkQlJFWlRMa1ZPVkRKTE1USXVSRTlOUVVsT0xrTlBUVEFlRncweE5EQXpNamd3TVRBMQpNek5hRncweU5EQXpNalV3TVRBMU16TmFNQ0l4SURBZUJnTlZCQU1NRjBGRVJsTXVSVTVVTWtzeE1pNUVUMDFCClNVNHVRMDlOTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyczlKa2VOQUhPa1EKMVFZSmdqZWZVd2Nhb2dFTWNhVy9rb0ErYnU5eGJyNHJIeS8yZ04va2M4T2tvUHV3Si9uTmxPSU8rcytNYm5YUwpMOW1VVEM0T0s3dHJrRWppS1hCK0QrVlNZeTZpbVhoNnpwQnROYmVaeXgrcmRCbmFPdjNCeVpSbm5FQjhMbWhNCnZIQSs0Zi90OWZ4LzJ2dDZ3UHgvL1ZnSXE5eXVZWVVRUkxtMVdqeVVCRnJaZUdvU3BQbTBLZXdtK0IwYmhtTWIKZHlDKzNmaGFLQytVazFOUG9kRTI5NzNqTEJaSmVsWnhzWlk0MFd3OHpZUXdkR1lJYlhxb1RjKzFhL3g0ZjFFbgptNEFOcWdnSHR3K05xOHpoc3MzeVR0WStVWUtEUkJJTGRMVlpRaEhKRXhlMGtBZWlzZ014SS9iQndPMUhickZWCit6U25rK252Z1FJREFRQUJvMll3WkRBekJnTlZIU1VFTERBcUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SUcKQ2lzR0FRUUJnamNVQWdJR0NDc0dBUVVGQndNRE1CMEdBMVVkRGdRV0JCVHlKVWZZNjZ6WWJtOWkweGVZSHVGSQo0TU43dURBT0JnTlZIUThCQWY4RUJBTUNCU0F3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQU01a3o5T0tOU3VYCjh3NE5PZ25mSUZkYXpkMG5QbElVYnZEVmZRb055OVEwUzFTRlVWTWVrSVBOaVZoZkd6eWE5SXdSdEdiMVZhQlEKQVEyT1JJekhyOEEycjVVTkx4M21GanBKbWVPeFF3bFYwWCtnOHMrMjUzS1ZGeE9wUkU2eXlhZ24vQnh4cHRUTAphMVo0cWVRSkxENDJsZDFxR2xSd0Z0VlJtVkZaelZYVnJwdTdOdUZkM3Zsbm5PL3FLV1hVK3VNc2ZYdHNsMTNuCmVjMWt3MUV3cTJqbks4V0ltS1RRNy85V2JhSVkwZ3g4bW93Q0pTT3NScTBURTd6Sy9ONTVkck4xd1hKVnhXZTUKNE4zMmVDcW90WHk5ajlsemRrTmE3YXdiOXEzOG5XVnhQK3ZhNWpxTklEbGxqQjZ0RXh5NW4zczd0NktLNmc1agpUWmdWcXJaMyttcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

# Uncomment one of the below options for authentication

#active_directory:
#  base: cn=users,dc=ent2k12,dc=domain,dc=com
#  host: "192.168.2.75"
#  port: "636"
#  bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
#  con_type: ldaps
#  srv_dns: "false"

#oidc:
#  client_id: xxxxxx
#  issuer: https://xxxxxx.okta.com/
#  user_in_idtoken: false
#  domain: ""
#  scopes: openid email profile groups
#  claims:
#    sub: sub
#    email: email
#    given_name: given_name
#    family_name: family_name
#    display_name: name
#    groups: groups

#github:
#  client_id: d85d77c55a08c9bcbb15
#  teams: TremoloSecurity/

saml:
  idp_url: "https://portal.apps.tremolo.io/idp-test/metadata/0c7e8a27-5e34-4d48-82df-b078a766f06b"




network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  #az_groups:
  #- CN=k8s-users,CN=Users,DC=ent2k12,DC=domain,DC=com

#myvd_configmap: myvdconfig

# For Namespace as a Service

#database:
#  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://mariadb.mariadb.svc.cluster.local:3306/unison
#  user: unison
#  validation: SELECT 1

#smtp:
#  host: blackhole.blackhole.svc.cluster.local
#  port: 1025
#  user: "none"
#  from: donotreply@domain.com
#  tls: false
`

**Comment by mlbiam** [comment]
with large quote blocks, can you paste it between ` ``` `?

for instances:

```
this: 
  is:
    a:
      large: code-block
```

**Comment by mlbiam** [comment]
> You need this setting if you want your API server to integrate with OpenUnison via OIDC. If you set enable_impersonation to true this value gets ignored.

Ignore this. I  have it backwards.  Sorry about that.

Your config looks OK.  We'll add something to `ouctl` that validates the webhooks are ready before launching the last helm chart.  

The error `[2022-07-11 14:52:41,125][XNIO-1 task-6] INFO AccessLog - [Error] - UNKNOWN - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - cn=none - NONE [127.0.0.1] - [f105ab0a8b812f65cbb5e242f35c7314fa3683878]` is expected until the `orchestra-login-portal` chart is deployed because that's when the identity provider is configured.  Is it still happening after the `orchestra-login-portal` chart is deployed?  If so, can you look in your logs for something like:

`[2022-07-11 15:38:04,205][main] INFO  LoadApplicationsFromK8s - Adding application anonfiles`?

**Comment by BrentRose** [comment]
Still getting this repeating in the logs.  I also grep'ed for LoadApplicatioinFromK8s and didn't see any results.

```
[2022-07-11 15:48:11,134][XNIO-1 task-14] INFO  AccessLog - [Error] - UNKNOWN - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - cn=none - NONE [127.0.0.1] - [f4c0f4986134c0831a2b1a640b5574720dbb06632]
[2022-07-11 15:48:11,134][XNIO-1 task-14] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Unknown URI : /auth/idp/k8sIdp/.well-known/openid-configuration
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:116) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) ~[unison-sdk-1.0.31.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:88) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:269) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) ~[unison-server-core-1.0.31.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) ~[unison-server-core-1.0.31.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) ~[undertow-servlet-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) ~[undertow-core-2.2.18.Final.jar:2.2.18.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-2.3.6.Final.jar:2.3.6.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) ~[jboss-threads-2.3.6.Final.jar:2.3.6.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) ~[jboss-threads-2.3.6.Final.jar:2.3.6.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) ~[jboss-threads-2.3.6.Final.jar:2.3.6.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.7.Final.jar:3.8.7.Final]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-07-11 15:48:11,156][XNIO-1 task-14] INFO  AccessLog - [AzSuccess] - CheckAlive - https://127.0.0.1:8443/check_alive - uid=Anonymous,o=Tremolo -  [127.0.0.1] - [fb97b539178113e9f123a4f23bb8e68aaf0d1bb67]
```

**Comment by BrentRose** [comment]
```
[QA\brose@atl1q51k8sb5n05 ou]$ kubectl get applications.openunison.tremolo.io -n openunison
No resources found in openunison namespace.

```

**Comment by BrentRose** [comment]
The `users` namespaces is where the service account I'm currently using to authenticate resides.

**Comment by BrentRose** [comment]
```
[QA\brose@atl1q51k8sb5n05 ou]$ helm upgrade orchestra-login-portal tremolo/orchestra-login-portal -f values.yaml -n openunison
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s": x509: certificate signed by unknown authority
```

**Comment by mlbiam** [comment]
> Ah... they do not match

great!  that gives us a good idea as to the issue.  look in the logs for the operator (label `openunison-operator`), any errors or exceptions in there?

**Comment by BrentRose** [comment]
Would it help if I try to remove the portal and deploy with helm using the correct namespace?  Maybe we got out of whack when I used the helm upgrade command without specifying the namespace?

**Comment by mlbiam** [comment]
What's your cluster built with?  Is it OpenShift?

**Comment by mlbiam** [comment]
huh, i mean YAY!  now, why does the operator think you're on openshift???

**Comment by BrentRose** [comment]
Possibly something to do with my nodes running on Fedora Core OS?

**Comment by mlbiam** [comment]
can you run `kubectl api-resources -o wide | grep openshift` ?

**Comment by BrentRose** [comment]
```
[QA\brose@atl1q51k8sb5n05 ou]$ kubectl api-resources | grep openshift
volumereplicationclasses          vrc               replication.storage.openshift.io/v1alpha1   false        VolumeReplicationClass
volumereplications                vr                replication.storage.openshift.io/v1alpha1   true         VolumeReplication
```

**Comment by BrentRose** [comment]
I can't say for sure but I'll bet this is related to our rook/ceph implementation.

**Comment by mlbiam** [comment]
Yep, that would do it.  OK, well we need to just get that disabled anyways.  It's not needed anymore and just causes lots of heartburn.  Thanks for the verification!

**Comment by BrentRose** [comment]
@mlbiam Thanks for your help getting my rolling on this!
