### ISSUE TITLE
open unison can't connect to AD server

### ISSUE THREAD

**Issue by Mihai-CMM** [OpenUnison/openunison-k8s#5]
Hello
I have one SA used to connect to AD - we use a non secured connection for this env that's why conn is set to ldap 

```
active_directory:
  base: "OU=Salt-Test,DC=salt-test,DC=ch"
  host: "10.192.14.2"
  port: "636"
 # bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
  bind_dn: "CN=k8s Service Account,OU=Domain-Service-Accounts,OU=Salt-Test,DC=salt-test,DC=ch"
  con_type: ldap
  srv_dns: "false"

```
Running ldapsearch command all seems ok

```
[mcostach@itsk8s01-cr-test ~]$ ldapsearch -x -b OU=Salt-Test,DC=salt-test,DC=ch -H ldap://10.192.14.2 -D "CN=k8s Service Account,OU=Domain-Service-Accounts,OU=Salt-Test,DC=salt-test,DC=ch" -W
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <OU=Salt-Test,DC=salt-test,DC=ch> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# Salt-Test, salt-test.ch
dn: OU=Salt-Test,DC=salt-test,DC=ch
objectClass: top
objectClass: organizationalUnit
ou: Salt-Test
distinguishedName: OU=Salt-Test,DC=salt-test,DC=ch
```
However I see the following errors on the pod logs

```

[2021-11-08 12:36:08,777][XNIO-1 task-4] INFO  AccessLog - SRCH op=10 con=9 base='o=Data' filter='(uid=adm_mcostach@salt-test.ch)' scope='2' attribs=''
[2021-11-08 12:36:08,777][XNIO-1 task-4] WARN  ConnectionWrapper - Connection stale, re-creating
[2021-11-08 12:36:08,795][XNIO-1 task-4] ERROR Router - Error running search
com.novell.ldap.LDAPException: Connect Error
        at com.novell.ldap.Connection.writeMessage(Connection.java:734) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.Message.sendMessage(Message.java:101) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.MessageAgent.sendMessage(MessageAgent.java:286) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.sendRequestToServer(LDAPConnection.java:3743) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.bind(LDAPConnection.java:1535) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.bind(LDAPConnection.java:1399) ~[jldap-1.0.0.jar:?]
        at net.sourceforge.myvd.inserts.ldap.ConnectionWrapper.bind(ConnectionWrapper.java:114) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.getConnection(LDAPConnectionPool.java:146) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.getConnection(LDAPConnectionPool.java:73) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:203) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:192) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.search(LDAPInterceptor.java:415) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.AttributeMapper.search(AttributeMapper.java:180) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.AttributeValueMapper.search(AttributeValueMapper.java:190) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.DNAttributeMapper.search(DNAttributeMapper.java:214) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.inserts.util.UUIDtoText.search(UUIDtoText.java:147) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.router.Router.search(Router.java:368) [myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:60) [myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.log.AccessLog.search(AccessLog.java:499) [unison-server-core-1.0.24.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) [myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.MyVDConnection.search(MyVDConnection.java:99) [unison-sdk-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.FormLoginAuthMech.doPost(FormLoginAuthMech.java:165) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:193) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) [unison-sdk-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:88) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:296) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) [unison-server-core-1.0.24.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) [xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException
        ... 71 more
[2021-11-08 12:36:08,796][XNIO-1 task-4] INFO  AccessLog - RESULT op=10 con=9 result=91 time=19
[2021-11-08 12:36:08,796][XNIO-1 task-4] ERROR FormLoginAuthMech - Could not authenticate user
com.novell.ldap.LDAPException: Connect Error
        at com.novell.ldap.Connection.writeMessage(Connection.java:734) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.Message.sendMessage(Message.java:101) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.MessageAgent.sendMessage(MessageAgent.java:286) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.sendRequestToServer(LDAPConnection.java:3743) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.bind(LDAPConnection.java:1535) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPConnection.bind(LDAPConnection.java:1399) ~[jldap-1.0.0.jar:?]
        at net.sourceforge.myvd.inserts.ldap.ConnectionWrapper.bind(ConnectionWrapper.java:114) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.getConnection(LDAPConnectionPool.java:146) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.getConnection(LDAPConnectionPool.java:73) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:203) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:192) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.search(LDAPInterceptor.java:415) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.AttributeMapper.search(AttributeMapper.java:180) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.AttributeValueMapper.search(AttributeValueMapper.java:190) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.inserts.mapping.DNAttributeMapper.search(DNAttributeMapper.java:214) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.inserts.util.UUIDtoText.search(UUIDtoText.java:147) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.router.Router.search(Router.java:368) ~[myvd-server-1.0.11.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:60) ~[myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.log.AccessLog.search(AccessLog.java:499) ~[unison-server-core-1.0.24.jar:?]
        at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.11.jar:?]
        at com.tremolosecurity.proxy.myvd.MyVDConnection.search(MyVDConnection.java:99) ~[unison-sdk-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.FormLoginAuthMech.doPost(FormLoginAuthMech.java:165) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:193) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) [unison-sdk-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:88) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:296) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.24.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) [unison-server-core-1.0.24.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) [undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) [undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) [xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException
        ... 71 more
```

Here is the secret description, where sa password is base 64 encoded
```
[mcostach@itsk8s01-cr-test ~]$ kubectl describe secret orchestra-secrets-source -n openunison
Name:         orchestra-secrets-source
Namespace:    openunison
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
AD_BIND_PASSWORD:        10 bytes
K8S_DB_SECRET:           10 bytes
unisonKeystorePassword:  10 bytes

```

Can you please let me know what i am doing wrong here.

**Comment by Mihai-CMM** [comment]
Sorry 
Bad user here- i needed to connect to port 389 for unsecured LDAP.

![image](https://user-images.githubusercontent.com/14325493/140750220-6f291b46-6deb-4aea-a3b6-5127dd1d8f11.png)


Thanks a lot
